### PR TITLE
changes for #5

### PR DESCRIPTION
**Pull request by ashishdawale20**

### CODE REVIEW

**Comment by ashishdawale20** [comment]
@avrum  can you please review this PR?

**Comment by avrum** [comment]
Hi,

Why do you want to add chars to the version regex?

**Comment by ashishdawale20** [comment]
@avrum 

Let say I have package.config with dev dependency: 
`<package id="Test" version="1.0.7201-dev" targetFramework="net461" />`

And nuspect with:
`<dependency id="Test" version="[1.0.7201-dev]" />
`
On building the project my nuspec getting changed to below with extra "-dev" as at this point our regex is only matching with number hence -- 1.0.7201 is the only thing get replaced by '1.0.7201-dev' causing extra -dev to be added all the time we build the project

`<dependency id="TestFramework.Common" version="**[1.0.7201-dev-dev]**" />`


I have tested this change on my project and it is working as expected

**Review by avrum — COMMENTED** [review]
Please note that the first part can't have chars
According to the link you sent me
https://docs.microsoft.com/en-us/nuget/create-packages/prerelease-packages
Please change the regex to match this pattern,
probably don't need to change the first [0-9]+ and only the second one
Whats your thought about it?

**Comment by ashishdawale20** [comment]
@avrum 
You are right, it should be the first part only. I have updated the file

**Comment by avrum** [comment]
Done,
Thanks for contributing the code

**Pull request merged**
